on:
  issues:
    types: [opened]
   
jobs:
  thank-user:
    runs-on: ubuntu-20.04
    name: Say thanks for the Issue
    steps:
      - name: comment on the issue
        uses: hasura/comment-progress@v2.2.0
        with:
          github-token: ${{ secrets.WANGZELIN_TOKEN }}
          repository: 'wangzelin007/github-bot-dev'
          number: ${{ github.event.issue.number }}
          id: thank-you-comment
          message: 'Thank you for opening this Issue :pray:'
