on:
  pull_request_target:
    types: [opened]

permissions: {}

jobs:
  get-message:
    runs-on: ubuntu-latest
    name: Get message from title
    permissions:
      contents: read
    steps:
      - name: Get message
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "TITLE: $TITLE"
          # Extract message from the title
          message=$(echo "$TITLE" | grep -oPm 1 '[{\[][^}\]]+[}\]]' | head -1 | sed 's/{\|}\|\[\|\]//g')

          # If no message found, set default message
          if [ -z "$message" ]; then
            message='Thank you for your contribution! We will review the pull request and get back to you soon.'
          fi

          # Print message for debugging
          echo "Message to be posted: $message end."

          # Write message to output.txt
          mkdir -p message_result
          echo "$message" > message_result/output.txt
      - name: Archive pr message
        uses: actions/upload-artifact@v4
        with:
          name: message-output
          path: |
            message_result/output.txt

  comment-pr:
    needs: [get-message]
    runs-on: ubuntu-latest
    name: Say thanks for the PR
    permissions:
      contents: read
    steps:
      - name: Download pr message
        uses: actions/download-artifact@v4
        with:
          name: message-output
      - name: Comment on the PR
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.WANGZELIN_TOKEN }}
        run: |
          # Read the message directly from the file
          message=$(cat ./output.txt)
          echo "Message: $message"

          # Comment on the PR using GitHub API
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments \
            -d "{\"body\": \"$message\"}"
