on:
  pull_request:
    types: [opened]
    
jobs:
  thank-user:
    runs-on: ubuntu-20.04
    name: Say thanks for the PR
    steps:
      - name: get message
        run: |
          echo "message=$(echo '${{ github.event.pull_request.title }}' | grep -oP '[{\[][^}\]]+[}\]]' | sed 's/{\|\[|\]|\}//g')" >> $GITHUB_ENV
          if [ -z "${{ env.message }}" ]; then
              echo "message=$(echo 'Thank you for your contribution! We will review the pull request and get back to you soon.')" >> $GITHUB_ENV
          fi
      - name: comment on the pull request
        uses: hasura/comment-progress@v2.2.0
        with:
          github-token: ${{ secrets.WANGZELIN_TOKEN }}
          repository: 'wangzelin007/github-bot-dev'
          number: ${{ github.event.number }}
          id: thank-you-comment
          message: "${{ env.message }}"
